# Generated by Django 5.2.9 on 2026-01-02 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='Empresa')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('interest', models.CharField(choices=[('solutions', 'Soluciones Empresas'), ('academy', 'IAlfabetización'), ('consulting', 'Consultoría Estratégica'), ('agents', 'Agentes Autónomos & RAG'), ('automation', 'Automatización (RPA + IA)'), ('other', 'Otro')], default='solutions', max_length=50, verbose_name='Área de interés')),
                ('message', models.TextField(blank=True, verbose_name='Mensaje')),
                ('status', models.CharField(choices=[('new', 'Nuevo'), ('contacted', 'Contactado'), ('qualified', 'Calificado'), ('proposal', 'Propuesta enviada'), ('closed_won', 'Cerrado ganado'), ('closed_lost', 'Cerrado perdido')], default='new', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas internas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('source', models.CharField(default='website', help_text='De dónde vino el lead (website, linkedin, referido, etc.)', max_length=50, verbose_name='Fuente')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
