# Generated by Django 5.2.9 on 2026-01-02 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Módulo del curso',
                'verbose_name_plural': 'Módulos del curso',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='Empresa')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('employees_count', models.CharField(blank=True, choices=[('1-10', '1-10 empleados'), ('11-50', '11-50 empleados'), ('51-200', '51-200 empleados'), ('200+', 'Más de 200 empleados')], max_length=20, verbose_name='Tamaño de empresa')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Email confirmado')),
                ('is_enrolled', models.BooleanField(default=False, verbose_name='Inscrito en programa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Inscripción lista de espera',
                'verbose_name_plural': 'Lista de espera',
                'ordering': ['-created_at'],
            },
        ),
    ]
