# Generated by Django 5.2.9 on 2026-01-02 23:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ID de sesión')),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email del usuario')),
                ('user_name', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actividad')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Contexto adicional: IP, user-agent, fuente, etc.', verbose_name='Metadatos')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('total_messages', models.PositiveIntegerField(default=0, verbose_name='Total mensajes')),
            ],
            options={
                'verbose_name': 'Sesión de chat',
                'verbose_name_plural': 'Sesiones de chat',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('source_url', models.URLField(blank=True, verbose_name='URL de origen')),
                ('category', models.CharField(choices=[('services', 'Servicios'), ('academy', 'IAlfabetización'), ('faq', 'Preguntas frecuentes'), ('company', 'Empresa'), ('technical', 'Documentación técnica')], default='faq', max_length=50, verbose_name='Categoría')),
                ('is_indexed', models.BooleanField(default=False, verbose_name='Indexado en vector DB')),
                ('indexed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de indexación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Documento de conocimiento',
                'verbose_name_plural': 'Base de conocimiento',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'Asistente'), ('system', 'Sistema')], max_length=20, verbose_name='Rol')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado')),
                ('embedding_id', models.CharField(blank=True, help_text='Referencia a vector DB (Pinecone, Qdrant, pgvector)', max_length=100, null=True, verbose_name='ID de embedding')),
                ('sources', models.JSONField(blank=True, default=list, help_text='Lista de documentos/chunks usados para la respuesta', verbose_name='Fuentes')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Tokens, modelo usado, latencia, etc.', verbose_name='Metadatos')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatsession', verbose_name='Sesión')),
            ],
            options={
                'verbose_name': 'Mensaje de chat',
                'verbose_name_plural': 'Mensajes de chat',
                'ordering': ['created_at'],
            },
        ),
    ]
