# Generated by Django 5.2.9 on 2026-01-04 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='history',
            field=models.JSONField(blank=True, default=list, help_text='Historial completo de la conversación (formato Gemini)', verbose_name='Historial'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='Resumen'),
        ),
    ]
